name: Build Raven

on:
  push:
    branches:
      - release*
  pull_request:
    branches:
      - master
      - develop
      - release*
  workflow_dispatch:
    # Adding manual trigger capability
    inputs:
      os_to_build:
        description: 'OS to build (leave empty for all)'
        required: false
        default: ''
        type: string

env:
  SCRIPTS: ${{ github.workspace }}/.github/scripts

jobs:
  check-jobs:
    runs-on: ubuntu-22.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'never'
          skip_after_successful_duplicate: 'true'
          paths_ignore: '[
                          "binaries/**",
                          "community/**",
                          "contrib/**",
                          "doc/**",
                          "roadmap/**",
                          "share/**",
                          "static-builds/**",
                          "whitepaper/**",
                          "**/*.md"
                          ]'
          do_not_skip: '["workflow_dispatch", "schedule"]'

  build:
    needs: check-jobs
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        OS: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.os_to_build != '' && fromJSON(format('["{0}"]', github.event.inputs.os_to_build)) || fromJSON('["windows", "linux", "linux-disable-wallet", "arm32v7", "arm32v7-disable-wallet", "aarch64", "aarch64-disable-wallet"]') }}

    steps:
    - if: ${{ needs.check-jobs.outputs.should_skip != 'true' || github.event_name == 'workflow_dispatch' }}
      name: Checkout the Code
      uses: actions/checkout@v3

    - if: ${{ needs.check-jobs.outputs.should_skip != 'true' || github.event_name == 'workflow_dispatch' }}
      name: Install Build Tools
      run: sudo ${SCRIPTS}/00-install-deps.sh ${{ matrix.OS }}

    - if: ${{ needs.check-jobs.outputs.should_skip != 'true' || github.event_name == 'workflow_dispatch' }}
      name: Cache dependencies.
      uses: actions/cache@v4
      with:
       path: |
        ${{ github.workspace }}/depends/built
        ${{ github.workspace }}/depends/sources
        ${{ github.workspace }}/depends/work
       key: ${{ matrix.OS }}-ubuntu22

    - if: ${{ needs.check-jobs.outputs.should_skip != 'true' || github.event_name == 'workflow_dispatch' }}
      name: Build dependencies.
      run: ${SCRIPTS}/02-copy-build-dependencies.sh ${{ matrix.OS }} ${{ github.workspace }} ${{ github.base_ref }} ${{ github.ref }}

    - if: ${{ needs.check-jobs.outputs.should_skip != 'true' || github.event_name == 'workflow_dispatch' }}
      name: Add Dependencies to the System PATH
      run: ${SCRIPTS}/03-export-path.sh ${{ matrix.OS }} ${{ github.workspace }}

    - if: ${{ needs.check-jobs.outputs.should_skip != 'true' || github.event_name == 'workflow_dispatch' }}
      name: Build Config
      run: cd ${{ github.workspace }} && ./autogen.sh

    - if: ${{ needs.check-jobs.outputs.should_skip != 'true' || github.event_name == 'workflow_dispatch' }}
      name: Configure Build
      run: ${SCRIPTS}/04-configure-build.sh ${{ matrix.OS }} ${{ github.workspace }}

    - if: ${{ needs.check-jobs.outputs.should_skip != 'true' || github.event_name == 'workflow_dispatch' }}
      name: Build Raven
      run: make -j2

    - if: ${{ needs.check-jobs.outputs.should_skip != 'true' || github.event_name == 'workflow_dispatch' }}
      name: Check Binary Security
      run: ${SCRIPTS}/05-binary-checks.sh ${{ matrix.OS }} ${{ github.workspace }}

    - if: ${{ needs.check-jobs.outputs.should_skip != 'true' || github.event_name == 'workflow_dispatch' }}
      name: Package Up the Build
      run: ${SCRIPTS}/06-package.sh ${{ matrix.OS }} ${{ github.workspace }} ${{ github.base_ref }} ${{ github.ref }}
    
    - if: ${{ needs.check-jobs.outputs.should_skip != 'true' || github.event_name == 'workflow_dispatch' }}
      name: Upload Artifacts to Job
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.OS }}
        path: ${{ github.workspace }}/release
