name: Build Raven

on:
  push:
    branches:
      - release*
  pull_request:
    branches:
      - master
      - develop
      - release*
  workflow_dispatch:
    # Adding manual trigger capability
    inputs:
      os_to_build:
        description: 'OS to build (leave empty for all)'
        required: false
        default: ''
        type: string
#    paths-ignore:
#      - 'binaries/**'
#      - 'community/**'
#      - 'contrib/**'
#      - 'doc/**'
#      - 'roadmap/**'
#      - 'share/**'
#      - 'static-builds/**'
#      - 'whitepaper/**'
#      - '*.md'

env:
  SCRIPTS: ${{ GITHUB.WORKSPACE }}/.github/scripts

jobs:
  check-jobs:
      # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-20.04
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          concurrent_skipping: 'never'
          skip_after_successful_duplicate: 'true'
          paths_ignore: '[
                          "binaries/**",
                          "community/**",
                          "contrib/**",
                          "doc/**",
                          "roadmap/**",
                          "share/**",
                          "static-builds/**",
                          "whitepaper/**",
                          "**/*.md"
                          ]'
          do_not_skip: '["workflow_dispatch", "schedule"]'

  build:
    needs: check-jobs
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        OS: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.os_to_build != '' && fromJSON(format('["{0}"]', github.event.inputs.os_to_build)) || fromJSON('["windows", "linux", "linux-disable-wallet", "arm32v7", "arm32v7-disable-wallet", "aarch64", "aarch64-disable-wallet"]') }}

    steps:
    - if: ${{ needs.check-jobs.outputs.should_skip != 'true' || github.event_name == 'workflow_dispatch' }}
      name: Checkout the Code
      uses: actions/checkout@v1

    - if: ${{ needs.check-jobs.outputs.should_skip != 'true' || github.event_name == 'workflow_dispatch' }}
      name: Install Build Tools
      run: sudo ${SCRIPTS}/00-install-deps.sh ${{ matrix.OS }}

    - if: ${{ needs.check-jobs.outputs.should_skip != 'true' || github.event_name == 'workflow_dispatch' }}
      name: Cache dependencies.
      uses: actions/cache@v4
      with:
       path: |
        ${{ GITHUB.WORKSPACE }}/depends/built
        ${{ GITHUB.WORKSPACE }}/depends/sources
        ${{ GITHUB.WORKSPACE }}/depends/work
       key: ${{ matrix.OS }}
      
    - if: ${{ needs.check-jobs.outputs.should_skip != 'true' || github.event_name == 'workflow_dispatch' }}
      name: Build dependencies.
      run: ${SCRIPTS}/02-copy-build-dependencies.sh ${{ matrix.OS }} ${{ GITHUB.WORKSPACE }} ${{ GITHUB.BASE_REF }} ${{ GITHUB.REF }}

    - if: ${{ needs.check-jobs.outputs.should_skip != 'true' || github.event_name == 'workflow_dispatch' }}
      name: Add Dependencies to the System PATH
      run: ${SCRIPTS}/03-export-path.sh ${{ matrix.OS }} ${{ GITHUB.WORKSPACE }}

    - if: ${{ needs.check-jobs.outputs.should_skip != 'true' || github.event_name == 'workflow_dispatch' }}
      name: Build Config
      run: cd ${{ GITHUB.WORKSPACE }} && ./autogen.sh

    - if: ${{ needs.check-jobs.outputs.should_skip != 'true' || github.event_name == 'workflow_dispatch' }}
      name: Configure Build
      run: ${SCRIPTS}/04-configure-build.sh ${{ matrix.OS }} ${{ GITHUB.WORKSPACE }}

    - if: ${{ needs.check-jobs.outputs.should_skip != 'true' || github.event_name == 'workflow_dispatch' }}
      name: Build Raven
      run: make -j2

    - if: ${{ needs.check-jobs.outputs.should_skip != 'true' || github.event_name == 'workflow_dispatch' }}
      name: Check Binary Security
      run: ${SCRIPTS}/05-binary-checks.sh ${{ matrix.OS }} ${{ GITHUB.WORKSPACE }}

    - if: ${{ needs.check-jobs.outputs.should_skip != 'true' || github.event_name == 'workflow_dispatch' }}
      name: Package Up the Build
      run: ${SCRIPTS}/06-package.sh ${{ matrix.OS }} ${{ GITHUB.WORKSPACE }} ${{ GITHUB.BASE_REF }} ${{ GITHUB.REF }}
    
    - if: ${{ needs.check-jobs.outputs.should_skip != 'true' || github.event_name == 'workflow_dispatch' }}
      name: Upload Artifacts to Job
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.OS }}
        path: ${{ GITHUB.WORKSPACE }}/release
